/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllInOneCalculator;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alamin
 */
public class AS extends javax.swing.JFrame {

    double firstNumber, secondNumber, result;

    public String operation;
    public int z = 0;

    /**
     * Creates new form AS
     */
    public AS() {
        //setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jOptionPane1 = new javax.swing.JOptionPane();
        sText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        xSquare = new javax.swing.JButton();
        xPower = new javax.swing.JButton();
        log = new javax.swing.JButton();
        xInverse = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        sinIn = new javax.swing.JButton();
        cosIn = new javax.swing.JButton();
        tanIn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        sAc = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sPluse = new javax.swing.JButton();
        sSeven = new javax.swing.JButton();
        sEight = new javax.swing.JButton();
        sNine = new javax.swing.JButton();
        sMinus = new javax.swing.JButton();
        sFour = new javax.swing.JButton();
        sFive = new javax.swing.JButton();
        sSix = new javax.swing.JButton();
        sMulti = new javax.swing.JButton();
        sOne = new javax.swing.JButton();
        sTwo = new javax.swing.JButton();
        sThree = new javax.swing.JButton();
        sDivide = new javax.swing.JButton();
        sEqual = new javax.swing.JButton();
        sPoint = new javax.swing.JButton();
        sZero = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setTitle("Scientific Calculator");

        sText.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        sText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        sText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTextActionPerformed(evt);
            }
        });

        xSquare.setBackground(new java.awt.Color(0, 0, 0));
        xSquare.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        xSquare.setForeground(new java.awt.Color(255, 255, 255));
        xSquare.setText("x^2");
        xSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xSquareActionPerformed(evt);
            }
        });

        xPower.setBackground(new java.awt.Color(0, 0, 0));
        xPower.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        xPower.setForeground(new java.awt.Color(255, 255, 255));
        xPower.setText("x^y");
        xPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPowerActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(0, 0, 0));
        log.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        xInverse.setBackground(new java.awt.Color(0, 0, 0));
        xInverse.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        xInverse.setForeground(new java.awt.Color(255, 255, 255));
        xInverse.setText("1/x");
        xInverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xInverseActionPerformed(evt);
            }
        });

        sqrt.setBackground(new java.awt.Color(0, 0, 0));
        sqrt.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sqrt.setForeground(new java.awt.Color(255, 255, 255));
        sqrt.setText("√");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        percent.setBackground(new java.awt.Color(0, 0, 0));
        percent.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        percent.setText("2π ");
        percent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        percent.setFocusable(false);
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentActionPerformed(evt);
            }
        });

        sinIn.setBackground(new java.awt.Color(0, 0, 0));
        sinIn.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        sinIn.setForeground(new java.awt.Color(255, 255, 255));
        sinIn.setText("sinh");
        sinIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinInActionPerformed(evt);
            }
        });

        cosIn.setBackground(new java.awt.Color(0, 0, 0));
        cosIn.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        cosIn.setForeground(new java.awt.Color(255, 255, 255));
        cosIn.setText("cosh");
        cosIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosInActionPerformed(evt);
            }
        });

        tanIn.setBackground(new java.awt.Color(0, 0, 0));
        tanIn.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        tanIn.setForeground(new java.awt.Color(255, 255, 255));
        tanIn.setText("tanh");
        tanIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanInActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("sin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("cos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("tan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("π ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Bin");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Oct");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Hex");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("x^3");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 8, 0));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllInOneCalculator/5050.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(244, 1, 1));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllInOneCalculator/d.png"))); // NOI18N
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(xSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xPower, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(sinIn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanIn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xPower, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xInverse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tanIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sinIn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(183, 17, 17));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DEL");
        jButton2.setToolTipText("");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sAc.setBackground(new java.awt.Color(183, 17, 17));
        sAc.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sAc.setForeground(new java.awt.Color(255, 255, 255));
        sAc.setText("AC");
        sAc.setToolTipText("");
        sAc.setFocusable(false);
        sAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAcActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("%");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sPluse.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sPluse.setText("+");
        sPluse.setFocusable(false);
        sPluse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPluseActionPerformed(evt);
            }
        });

        sSeven.setBackground(new java.awt.Color(0, 0, 0));
        sSeven.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sSeven.setForeground(new java.awt.Color(255, 255, 255));
        sSeven.setText("7");
        sSeven.setFocusable(false);
        sSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSevenActionPerformed(evt);
            }
        });

        sEight.setBackground(new java.awt.Color(0, 0, 0));
        sEight.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sEight.setForeground(new java.awt.Color(255, 255, 255));
        sEight.setText("8");
        sEight.setFocusable(false);
        sEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEightActionPerformed(evt);
            }
        });

        sNine.setBackground(new java.awt.Color(0, 0, 0));
        sNine.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sNine.setForeground(new java.awt.Color(255, 255, 255));
        sNine.setText("9");
        sNine.setFocusable(false);
        sNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNineActionPerformed(evt);
            }
        });

        sMinus.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sMinus.setText("-");
        sMinus.setFocusable(false);
        sMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMinusActionPerformed(evt);
            }
        });

        sFour.setBackground(new java.awt.Color(0, 0, 0));
        sFour.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sFour.setForeground(new java.awt.Color(255, 255, 255));
        sFour.setText("4");
        sFour.setFocusable(false);
        sFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFourActionPerformed(evt);
            }
        });

        sFive.setBackground(new java.awt.Color(0, 0, 0));
        sFive.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sFive.setForeground(new java.awt.Color(255, 255, 255));
        sFive.setText("5");
        sFive.setFocusable(false);
        sFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFiveActionPerformed(evt);
            }
        });

        sSix.setBackground(new java.awt.Color(0, 0, 0));
        sSix.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sSix.setForeground(new java.awt.Color(255, 255, 255));
        sSix.setText("6");
        sSix.setFocusable(false);
        sSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSixActionPerformed(evt);
            }
        });

        sMulti.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sMulti.setText("*");
        sMulti.setFocusable(false);
        sMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMultiActionPerformed(evt);
            }
        });

        sOne.setBackground(new java.awt.Color(0, 0, 0));
        sOne.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sOne.setForeground(new java.awt.Color(255, 255, 255));
        sOne.setText("1");
        sOne.setFocusable(false);
        sOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sOneActionPerformed(evt);
            }
        });

        sTwo.setBackground(new java.awt.Color(0, 0, 0));
        sTwo.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sTwo.setForeground(new java.awt.Color(255, 255, 255));
        sTwo.setText("2");
        sTwo.setFocusable(false);
        sTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTwoActionPerformed(evt);
            }
        });

        sThree.setBackground(new java.awt.Color(0, 0, 0));
        sThree.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sThree.setForeground(new java.awt.Color(255, 255, 255));
        sThree.setText("3");
        sThree.setFocusable(false);
        sThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sThreeActionPerformed(evt);
            }
        });

        sDivide.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sDivide.setText("/");
        sDivide.setFocusable(false);
        sDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDivideActionPerformed(evt);
            }
        });

        sEqual.setBackground(new java.awt.Color(0, 153, 51));
        sEqual.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        sEqual.setForeground(new java.awt.Color(255, 255, 255));
        sEqual.setText("=");
        sEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEqualActionPerformed(evt);
            }
        });

        sPoint.setBackground(new java.awt.Color(0, 0, 0));
        sPoint.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sPoint.setForeground(new java.awt.Color(255, 255, 255));
        sPoint.setText(".");
        sPoint.setFocusable(false);
        sPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPointActionPerformed(evt);
            }
        });

        sZero.setBackground(new java.awt.Color(0, 0, 0));
        sZero.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        sZero.setForeground(new java.awt.Color(255, 255, 255));
        sZero.setText("0");
        sZero.setFocusable(false);
        sZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sZeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sEight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sNine, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sAc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sPluse, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sFour, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sFive, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sSix, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sOne, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sThree, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sZero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPluse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sEight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sFour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sFive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sSix, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sOne, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sThree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sZero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu2.setText("Mode");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Basic");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Interest");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Currency");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Info");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sText)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(sText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String s = sText.getText();
            s = s.substring(0, s.length() - 1);
            sText.setText(s);
            if (s.length() == -1) {
                sText.setText("");
            }
        } catch (StringIndexOutOfBoundsException e) {
            sText.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAcActionPerformed
        sText.setText(null);
        z = 0;
    }//GEN-LAST:event_sAcActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            double percentage = Double.parseDouble(sText.getText()) / 100;
            String answer = String.format("%.3f", percentage);
            sText.setText(answer);
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sPluseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPluseActionPerformed
        // sText.setText("+");
        try {
            firstNumber = Double.parseDouble(sText.getText());
            sText.setText("");
            operation = "+";
            z = 0;
        } catch (NumberFormatException e) {
            sText.setText("");
        }

    }//GEN-LAST:event_sPluseActionPerformed

    private void sSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSevenActionPerformed
        //sText.setText(sText.getText()+"7");
        String enter = sText.getText() + sSeven.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sSevenActionPerformed

    private void sEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEightActionPerformed
        // sText.setText(sText.getText()+"8");
        String enter = sText.getText() + sEight.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sEightActionPerformed

    private void sNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNineActionPerformed
        //       sText.setText(sText.getText()+"9");
        String enter = sText.getText() + sNine.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sNineActionPerformed

    private void sMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMinusActionPerformed
        //sText.setText("-");
        try {
            firstNumber = Double.parseDouble(sText.getText());
            sText.setText("");
            operation = "-";
            z = 0;
        } catch (NumberFormatException e) {
            sText.setText("");
        }

    }//GEN-LAST:event_sMinusActionPerformed

    private void sFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFourActionPerformed
        //sText.setText(sText.getText()+"4");
        String enter = sText.getText() + sFour.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sFourActionPerformed

    private void sFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFiveActionPerformed
        //sText.setText(sText.getText()+"5");
        String enter = sText.getText() + sFive.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sFiveActionPerformed

    private void sSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSixActionPerformed
        //sText.setText(sText.getText()+"6");
        String enter = sText.getText() + sSix.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sSixActionPerformed

    private void sMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMultiActionPerformed
        //sText.setText("*");

        try {
            firstNumber = Double.parseDouble(sText.getText());
            sText.setText("");
            operation = "*";
            z = 0;
        } catch (NumberFormatException e) {
            sText.setText("");
        }

    }//GEN-LAST:event_sMultiActionPerformed

    private void sOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sOneActionPerformed
        //sText.setText(sText.getText()+"1");
        String enter = sText.getText() + sOne.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sOneActionPerformed

    private void sTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTwoActionPerformed
        //sText.setText(sText.getText()+"2");
        String enter = sText.getText() + sTwo.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sTwoActionPerformed

    private void sThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sThreeActionPerformed
        //sText.setText(sText.getText()+"3");
        String enter = sText.getText() + sThree.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sThreeActionPerformed

    private void sDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDivideActionPerformed
        try {
            firstNumber = Double.parseDouble(sText.getText());
            sText.setText("");
            operation = "/";
            z = 0;
        } catch (NumberFormatException e) {
            sText.setText("");
        }

    }//GEN-LAST:event_sDivideActionPerformed

    private void sEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEqualActionPerformed

        String answer = "";
        String x = "";

        try {

            secondNumber = Double.parseDouble(sText.getText());

            if (operation == "+") {
                result = firstNumber + secondNumber;
                answer = String.format("%.2f", result);
                sText.setText(answer);
                x = "" + firstNumber + "+" + secondNumber+"="+answer;

            } else if (operation == "-") {
                result = firstNumber - secondNumber;
                answer = String.format("%.2f", result);
                sText.setText(answer);
                x = "" + firstNumber + "-" + secondNumber + "=" + answer;

            } else if (operation == "*") {
                result = firstNumber * secondNumber;
                answer = String.format("%.2f", result);
                sText.setText(answer);
                x = "" + firstNumber + "x" + secondNumber + "=" + answer;

            } else if (operation == "/") {
                result = firstNumber / secondNumber;
                answer = String.format("%.2f", result);

                sText.setText(answer);
                x = "" + firstNumber + "/" + secondNumber + "=" + answer;

            } else if (operation == "x^y") {
                result = Math.pow(firstNumber, secondNumber);
                answer = String.format("%.2f", result);
                sText.setText(answer);
                x = "" + firstNumber + "^" + secondNumber + "=" + answer;

            } else if (operation == "x/y") {
                result = Math.pow(10, secondNumber);
                answer = String.format("%.2f", result);
                sText.setText(answer);
                x = "" + firstNumber + "^" + secondNumber + "=" + answer;
            }

            writeToFile(x);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Syntax ERROR.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(AS.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_sEqualActionPerformed

    private void sPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPointActionPerformed
        //sText.setText(sText.getText()+".");
        if (z == 0) {
            String enter = sText.getText() + sPoint.getText();
            sText.setText(enter);
            z = 1;
        }

    }//GEN-LAST:event_sPointActionPerformed

    private void sZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sZeroActionPerformed
        //sText.setText(sText.getText()+"0");
        String enter = sText.getText() + sZero.getText();
        sText.setText(enter);
    }//GEN-LAST:event_sZeroActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed

        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            ops = Math.sqrt(ops);
            sText.setText(String.valueOf(ops));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }

    }//GEN-LAST:event_sqrtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            double rd;
            if (ops == 0) {

                sText.setText("0");
            } else if (ops == 30) {

                sText.setText("1/2");
            } else if (ops == 45) {
                sText.setText("1/√2");

            } else if (ops == 60) {
                sText.setText("√3/2");

            } else if (ops == 90) {

                sText.setText("1");
            } else if (ops == 180) {
                sText.setText("0");

            } else {

                rd = Math.sin(Math.toRadians(ops));
                sText.setText(String.format("%.5f", rd));

            }
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void sinInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinInActionPerformed
        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            double rd = Math.sinh(Math.toRadians(ops));
            sText.setText(String.format("%.5f", rd));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }


    }//GEN-LAST:event_sinInActionPerformed

    private void xPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPowerActionPerformed
try{        firstNumber = Double.parseDouble(String.valueOf(sText.getText()));
        //ops=Math.pow(a, b)
//				firstNumber=Double.parseDouble(textField1.getText());
        sText.setText("");
        operation = "x^y";
                } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_xPowerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            double ops = Double.parseDouble(sText.getText());
            double rd = 0;
            if (ops == 0) {

                sText.setText("1");
            } else if (ops == 30) {

                sText.setText("√3/2");
            } else if (ops == 45) {
                sText.setText("1/√2");

            } else if (ops == 60) {
                sText.setText("1/2");

            } else if (ops == 90) {
                //  rd= Math.cos(Math.toRadians(ops));
                //sText.setText(String.format("%.2f",rd));
                sText.setText("0");
            } else if (ops == 180) {
                sText.setText("-1");

            } else {

                rd = Math.cos(Math.toRadians(ops));
                sText.setText(String.format("%.5f", rd));
            }
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void cosInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosInActionPerformed

        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            ops = Math.toRadians(ops);
            double rd = Math.cosh(ops);
            sText.setText(String.valueOf(rd));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_cosInActionPerformed

    private void xSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xSquareActionPerformed
try{        double ops = Double.parseDouble(String.valueOf(sText.getText()));
        ops = ops * ops;
        sText.setText(String.valueOf(ops));
                } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_xSquareActionPerformed

    private void xInverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xInverseActionPerformed
        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            ops = 1 / ops;
            sText.setText(String.valueOf(ops));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_xInverseActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            double rd;
            if (ops == 0) {

                sText.setText("0");
            } else if (ops == 30) {

                sText.setText("1/√3");
            } else if (ops == 45) {
                sText.setText("1");

            } else if (ops == 60) {
                sText.setText("√3");

            } else if (ops == 90) {

                sText.setText("0");
            } else if (ops == 180) {
                sText.setText("Math ERROR");

            } else {

                rd = Math.tan(Math.toRadians(ops));
                sText.setText(String.format("%.5f", rd));

            }
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void tanInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanInActionPerformed
        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            ops = Math.toRadians(ops);
            double rd = Math.tanh(ops);
            sText.setText(String.valueOf(rd));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }

    }//GEN-LAST:event_tanInActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            long a = Integer.parseInt(String.valueOf(sText.getText()));
            long ans = fact(a);
            sText.setText(String.valueOf(ans));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
try{        int a = Integer.parseInt(String.valueOf(sText.getText()));
        sText.setText(Integer.toBinaryString(a));
                } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       try{ int a = Integer.parseInt(String.valueOf(sText.getText()));
        sText.setText(Integer.toHexString(a));}
                catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed

        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            ops = Math.log10(ops);
            sText.setText(String.valueOf(ops));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }

    }//GEN-LAST:event_logActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
try{        int a = Integer.parseInt(String.valueOf(sText.getText()));
        sText.setText(Integer.toOctalString(a));
                } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        double ops = Math.PI;

        sText.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Interest in = new Interest();

        in.setVisible(true);
        in.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Currency c = new Currency();
        c.pack();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Normal n = new Normal();
        n.pack();
        n.setLocationRelativeTo(null);
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        readFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        ImageIcon icon = new ImageIcon("bin50x50yjk-removebg-preview.png");
        int des = JOptionPane.showConfirmDialog(null, "Do You want to delete all History?", "File", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (des == 0) {
            clearFile();
            JOptionPane.showMessageDialog(null, "History Deleted Successfully", "InfoBox: " + "Deleted", JOptionPane.INFORMATION_MESSAGE);
        } else
            JOptionPane.showMessageDialog(null, "Uh-oh! No History Found.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentActionPerformed
        double ops = 2 * Math.PI;

        sText.setText(String.valueOf(ops));
    }//GEN-LAST:event_percentActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            double ops = Double.parseDouble(String.valueOf(sText.getText()));
            ops = ops * ops * ops;
            sText.setText(String.valueOf(ops));
        } catch (NumberFormatException e) {
            sText.setText("Syntax ERROR");
        } catch (ArrayIndexOutOfBoundsException e) {
            sText.setText("Syntax ERROR");
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      Info in=new Info();
      in.setVisible(true);
      in.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AS().setVisible(true);
            }
        });
    }

    public long fact(long n) {
        return n == 1 ? 1 : n * fact(n - 1);
    }

    private void writeToFile(String a) throws IOException {

        File f = new File("History.txt");
        //System.out.println(f);
        FileWriter fw = new FileWriter(f, true);
        //System.out.println(fw);
        try {
            BufferedWriter bw = new BufferedWriter(fw);
            //System.out.println(bw);
            bw.newLine();
            bw.write(a);
            //bw.flush();
            bw.close();
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void readFile() {

        File f = new File("History.txt");
        try {
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            StringBuilder sb = new StringBuilder();
            while (br.ready()) {
                Scanner input = new Scanner(f);
                while (input.hasNextLine()) {

                    String msg = input.nextLine();
                    sb.append(msg);
                    sb.append("    \n");

                }
                JOptionPane.showMessageDialog(percent, sb.toString());
                input.close();
                break;
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void clearFile() {
        try {
            FileWriter fwOb = new FileWriter("History.txt", false);
            PrintWriter pwOb = new PrintWriter(fwOb, false);
            pwOb.flush();
            pwOb.close();
            fwOb.close();
        } catch (IOException ioe) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cosIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JButton log;
    private javax.swing.JButton percent;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton sAc;
    private javax.swing.JButton sDivide;
    private javax.swing.JButton sEight;
    private javax.swing.JButton sEqual;
    private javax.swing.JButton sFive;
    private javax.swing.JButton sFour;
    private javax.swing.JButton sMinus;
    private javax.swing.JButton sMulti;
    private javax.swing.JButton sNine;
    private javax.swing.JButton sOne;
    private javax.swing.JButton sPluse;
    private javax.swing.JButton sPoint;
    private javax.swing.JButton sSeven;
    private javax.swing.JButton sSix;
    private javax.swing.JTextField sText;
    private javax.swing.JButton sThree;
    private javax.swing.JButton sTwo;
    private javax.swing.JButton sZero;
    private javax.swing.JButton sinIn;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton tanIn;
    private javax.swing.JButton xInverse;
    private javax.swing.JButton xPower;
    private javax.swing.JButton xSquare;
    // End of variables declaration//GEN-END:variables
}
