/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AllInOneCalculator;

import javax.swing.JOptionPane;
import java.lang.NumberFormatException;

/**
 *
 * @author Alami
 */
public class Normal extends javax.swing.JFrame {
    double firstNumber, secondNumber, result;
	
	String operation;
        
	
//	/**
//	 * Create the application.
//	 */

    /**
     * Creates new form Normal
     */
    public Normal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        sText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sAc = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sPluse = new javax.swing.JButton();
        sSeven = new javax.swing.JButton();
        sEight = new javax.swing.JButton();
        sNine = new javax.swing.JButton();
        sMinus = new javax.swing.JButton();
        sFour = new javax.swing.JButton();
        sFive = new javax.swing.JButton();
        sSix = new javax.swing.JButton();
        sMulti = new javax.swing.JButton();
        sOne = new javax.swing.JButton();
        sTwo = new javax.swing.JButton();
        sThree = new javax.swing.JButton();
        sDivide = new javax.swing.JButton();
        sEqual = new javax.swing.JButton();
        sPoint = new javax.swing.JButton();
        sZero = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        sText.setBackground(new java.awt.Color(51, 51, 51));
        sText.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        sText.setForeground(new java.awt.Color(255, 255, 255));
        sText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sText.setText(" ");

        jButton1.setBackground(new java.awt.Color(183, 17, 17));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DEL");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sAc.setBackground(new java.awt.Color(183, 17, 17));
        sAc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sAc.setForeground(new java.awt.Color(255, 255, 255));
        sAc.setText("AC");
        sAc.setToolTipText("");
        sAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAcActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("%");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sPluse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sPluse.setText("+");
        sPluse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPluseActionPerformed(evt);
            }
        });

        sSeven.setBackground(new java.awt.Color(0, 0, 0));
        sSeven.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sSeven.setForeground(new java.awt.Color(255, 255, 255));
        sSeven.setText("7");
        sSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSevenActionPerformed(evt);
            }
        });

        sEight.setBackground(new java.awt.Color(0, 0, 0));
        sEight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sEight.setForeground(new java.awt.Color(255, 255, 255));
        sEight.setText("8");
        sEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEightActionPerformed(evt);
            }
        });

        sNine.setBackground(new java.awt.Color(0, 0, 0));
        sNine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sNine.setForeground(new java.awt.Color(255, 255, 255));
        sNine.setText("9");
        sNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNineActionPerformed(evt);
            }
        });

        sMinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sMinus.setText("-");
        sMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMinusActionPerformed(evt);
            }
        });

        sFour.setBackground(new java.awt.Color(0, 0, 0));
        sFour.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sFour.setForeground(new java.awt.Color(255, 255, 255));
        sFour.setText("4");
        sFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFourActionPerformed(evt);
            }
        });

        sFive.setBackground(new java.awt.Color(0, 0, 0));
        sFive.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sFive.setForeground(new java.awt.Color(255, 255, 255));
        sFive.setText("5");
        sFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFiveActionPerformed(evt);
            }
        });

        sSix.setBackground(new java.awt.Color(0, 0, 0));
        sSix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sSix.setForeground(new java.awt.Color(255, 255, 255));
        sSix.setText("6");
        sSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSixActionPerformed(evt);
            }
        });

        sMulti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sMulti.setText("*");
        sMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMultiActionPerformed(evt);
            }
        });

        sOne.setBackground(new java.awt.Color(0, 0, 0));
        sOne.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sOne.setForeground(new java.awt.Color(255, 255, 255));
        sOne.setText("1");
        sOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sOneActionPerformed(evt);
            }
        });

        sTwo.setBackground(new java.awt.Color(0, 0, 0));
        sTwo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sTwo.setForeground(new java.awt.Color(255, 255, 255));
        sTwo.setText("2");
        sTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTwoActionPerformed(evt);
            }
        });

        sThree.setBackground(new java.awt.Color(0, 0, 0));
        sThree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sThree.setForeground(new java.awt.Color(255, 255, 255));
        sThree.setText("3");
        sThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sThreeActionPerformed(evt);
            }
        });

        sDivide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sDivide.setText("/");
        sDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDivideActionPerformed(evt);
            }
        });

        sEqual.setBackground(new java.awt.Color(0, 153, 51));
        sEqual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sEqual.setForeground(new java.awt.Color(255, 255, 255));
        sEqual.setText("=");
        sEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sEqualActionPerformed(evt);
            }
        });

        sPoint.setBackground(new java.awt.Color(0, 0, 0));
        sPoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sPoint.setForeground(new java.awt.Color(255, 255, 255));
        sPoint.setText(".");
        sPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPointActionPerformed(evt);
            }
        });

        sZero.setBackground(new java.awt.Color(0, 0, 0));
        sZero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sZero.setForeground(new java.awt.Color(255, 255, 255));
        sZero.setText("0");
        sZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sZeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sEight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sNine, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sAc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sPluse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sFour, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sFive, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sSix, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sOne, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sThree, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sZero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPluse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sEight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sFour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sFive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sSix, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sOne, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sThree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sZero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setForeground(new java.awt.Color(51, 255, 255));

        jMenu1.setText("Mode");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Interest");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Currency");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem4.setText("info");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       AS s1=new AS();
       s1.setVisible(true);
       s1.setLocationRelativeTo(null);
       dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void sSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSevenActionPerformed
        //sText.setText(sText.getText()+"7");
        String enter = sText.getText()+ sSeven.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sSevenActionPerformed

    private void sEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEightActionPerformed
        // sText.setText(sText.getText()+"8");
        String enter = sText.getText()+ sEight.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sEightActionPerformed

    private void sNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNineActionPerformed
//       sText.setText(sText.getText()+"9");
String enter = sText.getText()+ sNine.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sNineActionPerformed

    private void sFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFourActionPerformed
        //sText.setText(sText.getText()+"4");
        String enter = sText.getText()+ sFour.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sFourActionPerformed

    private void sFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFiveActionPerformed
        //sText.setText(sText.getText()+"5");
        String enter = sText.getText()+ sFive.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sFiveActionPerformed

    private void sSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSixActionPerformed
        //sText.setText(sText.getText()+"6");
        String enter = sText.getText()+ sSix.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sSixActionPerformed

    private void sOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sOneActionPerformed
         //sText.setText(sText.getText()+"1");
         String enter = sText.getText()+ sOne.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sOneActionPerformed

    private void sTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTwoActionPerformed
         //sText.setText(sText.getText()+"2");
         String enter = sText.getText()+ sTwo.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sTwoActionPerformed

    private void sThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sThreeActionPerformed
        //sText.setText(sText.getText()+"3");
        String enter = sText.getText()+ sThree.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sThreeActionPerformed

    private void sPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPointActionPerformed
         //sText.setText(sText.getText()+".");
         String enter = sText.getText()+ sPoint.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sPointActionPerformed

    private void sZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sZeroActionPerformed
        //sText.setText(sText.getText()+"0");
        String enter = sText.getText()+ sZero.getText();
				sText.setText(enter);
    }//GEN-LAST:event_sZeroActionPerformed

    private void sPluseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPluseActionPerformed
       // sText.setText("+");
        try{
           firstNumber=Double.parseDouble(sText.getText()); 
           sText.setText("");
				operation="+";
       }
       catch(NumberFormatException e)
       {
            sText.setText("");
       }
         
    }//GEN-LAST:event_sPluseActionPerformed

    private void sMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMinusActionPerformed
         //sText.setText("-");
          try{
           firstNumber=Double.parseDouble(sText.getText()); 
           sText.setText("");
				operation="-";
       }
       catch(NumberFormatException e)
       {
            sText.setText("");
       }
          
    }//GEN-LAST:event_sMinusActionPerformed

    private void sMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMultiActionPerformed
       //sText.setText("*");
       
       try{
           firstNumber=Double.parseDouble(sText.getText()); 
           sText.setText("");
				operation="*";
       }
       catch(NumberFormatException e)
       {
            sText.setText("");
       }
				
    }//GEN-LAST:event_sMultiActionPerformed

    private void sDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDivideActionPerformed
     try{
           firstNumber=Double.parseDouble(sText.getText()); 
           sText.setText("");
				operation="/";
       }
       catch(NumberFormatException e)
       {
            sText.setText("");
       }
        
       
       
    }//GEN-LAST:event_sDivideActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
            String s= sText.getText();
            s=s.substring(0,s.length()-1);
            sText.setText(s);
            if(s.length()==-1)
            {
                sText.setText("");
            }
        }
        catch(StringIndexOutOfBoundsException e){
            sText.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAcActionPerformed
       sText.setText(null);
    }//GEN-LAST:event_sAcActionPerformed

    private void sEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sEqualActionPerformed
       String answer;
      
       try{
           secondNumber=Double.parseDouble(sText.getText());
				
				if (operation=="+") {
					result=firstNumber+secondNumber;
					answer=String.format("%.2f", result);
					sText.setText(answer);
					
				} else if (operation=="-") {
					result=firstNumber-secondNumber;
					answer=String.format("%.2f", result);
					sText.setText(answer);
					
				} else if (operation=="*") {
					result=firstNumber*secondNumber;
					answer=String.format("%.2f", result);
					sText.setText(answer);
					
				} else if (operation=="/") {
					result=firstNumber/secondNumber;
					answer=String.format("%.2f", result);
					sText.setText(answer);
					
				}
       }
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(rootPane,"Syntax ERROR","Error",JOptionPane.ERROR_MESSAGE); 
       }
       catch(ArrayIndexOutOfBoundsException e){
     sText.setText("Syntax ERROR");
}
       
				
    }//GEN-LAST:event_sEqualActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
				
				
                                try{
                                    double percentage=Double.parseDouble(sText.getText())/100;
           String answer=String.format("%.3f", percentage);
           sText.setText(answer);
        }
                                
        catch(NumberFormatException e){
            sText.setText("Syntax ERROR");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      Interest in=new Interest();
      in.setVisible(true);
       in.setLocationRelativeTo(null);
      dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Currency c=new Currency();
        c.setVisible(true);
         c.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       
        Info s=new Info();
        s.setVisible(true);
        s.setLocationRelativeTo(null);
      //
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Normal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Normal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sAc;
    private javax.swing.JButton sDivide;
    private javax.swing.JButton sEight;
    private javax.swing.JButton sEqual;
    private javax.swing.JButton sFive;
    private javax.swing.JButton sFour;
    private javax.swing.JButton sMinus;
    private javax.swing.JButton sMulti;
    private javax.swing.JButton sNine;
    private javax.swing.JButton sOne;
    private javax.swing.JButton sPluse;
    private javax.swing.JButton sPoint;
    private javax.swing.JButton sSeven;
    private javax.swing.JButton sSix;
    private javax.swing.JTextField sText;
    private javax.swing.JButton sThree;
    private javax.swing.JButton sTwo;
    private javax.swing.JButton sZero;
    // End of variables declaration//GEN-END:variables
}
